# Generated by Django 2.0.1 on 2018-01-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointofSale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Cost',
            field=models.IntegerField(default=0),
        ),
    ]
