# Generated by Django 2.0.1 on 2018-02-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PointofSale', '0003_auto_20180131_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCostP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Total_Cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'total_cost_p_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalCostS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Total_Cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'total_cost_s_v',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='Type',
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PointofSale.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PointofSale.Product'),
        ),
    ]
