# Generated by Django 2.0.1 on 2018-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointofSale', '0004_auto_20180201_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=models.SET('Deleted_Product'), to='PointofSale.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=models.SET('Deleted_Product'), to='PointofSale.Product'),
        ),
    ]
